# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iotlt-connpass-updater3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e3ba9cf3c97c48b9a8e1bbfc6339e14b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3cdc35f17bc41e3a13e3795e0b35fed }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e3ba9cf3c97c48b9a8e1bbfc6339e14b }}/horihiro/node-puppeteer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iotlt-connpass-updater3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a33f117094c465d9ed519d6679415df }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e3ba9cf3c97c48b9a8e1bbfc6339e14b }}/horihiro/node-puppeteer:${{ github.sha }}'